### ISSUE TITLE
Calling for Collaboration to proposing an EVM-Compatible Version of DMC

### ISSUE THREAD

**Issue by Synthintel** [datamallchain/dmchain#1]
I recently participated in the OKX Hackathon and learned about DMC and its Nash consensus. As a developer, I must say, I am very impressed with the concept of Nash consensus, which is quite different from the common decentralized storage solutions available today. I believe you may have found the key to solving the issues with decentralized storage, but unfortunately, the adoption of this solution has not been widespread. This is possibly due to a lack of effort in promoting and developing the project.

I have been following your progress on Github, and I must say, it's quite disappointing to see such little activity on the platform. As a developer myself, I know the importance of transparency and collaboration in building a successful project. Instead, it seems like you are developing behind closed doors in a small circle, which is not a good sign for a decentralized project.

Moreover, I am puzzled by your choice of EOS as the underlying infrastructure. Is it just because of the low transaction fees? As a user who lost money investing in EOS, I find it difficult to understand why you would choose a platform that has a questionable track record. Additionally, as DMC's core is a set of contracts, I would recommend that you embrace the new public chain ecosystem and consider other alternatives that are more developer-friendly.

As a developer, I am excited about the idea of Nash consensus and its potential to revolutionize decentralized storage. However, I am disappointed with the lack of progress in the DMC project. Therefore, I plan to rally my friends and colleagues to implement an EVM-compatible version of DMC. I believe that with our collective efforts, we can overcome the technical challenges involved in implementing this version.

I hope that you will be open to collaboration and provide us with the necessary support to make this project a reality. I look forward to hearing back from you soon.

Best regards

**Comment by Synthintel** [comment]
Thank you for the Chairman's reply ^ ^ 

I also look forward to the DMC development team open-sourcing the relevant system as soon as possible, as it can be difficult to understand many concepts by only reading the yellow paper. I believe that open-sourcing the code will not only benefit the community's understanding of the technology but also accelerate its development and adoption

I am developing an EVM-compatible version of the DMC contract for personal purposes (in order to gain a better understanding of Nash consensus). I do not currently believe that this implementation alone can become another implementation of DMC.

But I believe that this process would be valuable for other engineers interested in Nash consensus, especially those familiar with smart contract development. Could you help me set up a repository? I can submit the code I am writing to it~~~

**Comment by victorweichen** [comment]
Sure. I am closely following the process of the chain development team's next release. In the meantime I will set up a repo for your EVM implementation ASAP.

**Comment by Synthintel** [comment]
I have completed the first version of DMC.sol to prove my enthusiasm for this project. I strongly believe that our discussions should be reflected in the code and I am eager to submit my work for review.

Therefore, I am requesting access to a repository where I can submit my code. I anticipate receiving prompt approval to commence with this process. I will post the code as soon as the repository is set up, and I look forward to feedback from the team. 
[dmc.sol](https://github.com/datamallchain/dmchain/files/11145230/dmc.txt)

**Comment by victorweichen** [comment]
Thank you for contributing to DMC chain! We are in the process of creating the Repo.

**Comment by kkilookx2** [comment]
Hi,Synthintel. We have already create a repository for the EVM compatible. Looking forward to future collaboration.
https://github.com/datamallchain/EVM-compatible

**Comment by Synthintel** [comment]
OK, I push the first version of dmc.sol to the repository.

**Comment by Synthintel** [comment]
My primary goal is to work together with my friends and other interested individuals to enhance the current implementation. I am aware that the existing implementation is still far from complete, and I believe that through collaborative efforts, we can make significant progress.

However, if the DMC Foundation has concerns or regulations regarding third-party repositories, I am more than willing to collaborate with my friends within my own repository first: https://github.com/Synthintel/dmc_solidity

**Comment by victorweichen** [comment]
I suggest to close this issue and refer further discussion regarding this topic to the new repostory. Thanks!
